#
# default otaks config
#

[server]
# address to bind
host = ""

    [server.app]
    port = 8087

    [server.api]
    port = 8080

    [server.web]
    port = 8888

    [server.logging]
    # server log level
    # ERROR | WARN | INFO | DEBUG | TRACE
    level = "INFO"

    # server log location
    # *only stdout supported*
    #location = "stdout"

[federation]
enabled = false

    [server.discordts]
    host = "discordtakserver.mooo.com"
    port = 48088
    protocol = "tcp"

    [server.fts]
    host = "204.48.30.216"
    port = 8087
    protocol = "tcp"