#
# default otaks config
#

[server]
# address to bind
host = ""

    [server.app]
    port = 8087

    [server.api]
    port = 8080

    [server.logging]
    # server log level
    # ERROR | WARN | INFO | DEBUG | TRACE
    level = "INFO"

    # server log location
    # *only stdout supported*
    #location = "stdout"
